<!DOCTYPE html>
<html>
<head>

	<meta charset="utf-8">
	<title><?= $this->title ?></title>
	
	<meta name="viewport" content="initial-scale=1, maximum-scale=1">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
	
	<meta name="application-name" content="Readr">
	<meta name="msapplication-TileColor" content="#3498DB">
	<meta name="msapplication-TileImage" content="<?= $this->basePath('public/img/readr-tile-144.png') ?>">
	
	<link rel="shortcut icon" href="<?= $this->basePath('favicon.ico') ?>">
	
	<link rel="apple-touch-icon" sizes="57x57" href="<?= $this->basePath('public/img/readr-icon-114.png') ?>">
	<link rel="apple-touch-icon" sizes="114x114" href="<?= $this->basePath('public/img/readr-icon-114.png') ?>">
	<link rel="apple-touch-icon" sizes="72x72" href="<?= $this->basePath('public/img/readr-icon-144.png') ?>">
	<link rel="apple-touch-icon" sizes="144x144" href="<?= $this->basePath('public/img/readr-icon-144.png') ?>">

	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,400italic,600italic">
	<link rel="stylesheet" type="text/css" href="<?= $this->basePath('public/css/readr.css') ?>">

	<script type="text/javascript" src="<?= $this->basePath('public/js/jquery.min.js') ?>"></script>
	<script type="text/javascript" src="<?= $this->basePath('public/js/jquery.hammer.min.js') ?>"></script>
	<script type="text/javascript" src="<?= $this->basePath('public/js/underscore-min.js') ?>"></script>
	<script type="text/javascript" src="<?= $this->basePath('public/js/underscore.string.min.js') ?>"></script>
	<script type="text/javascript" src="<?= $this->basePath('public/js/moment.min.js') ?>"></script>
	<script type="text/javascript" src="<?= $this->basePath('public/js/backbone-min.js') ?>"></script>
	<script type="text/javascript" src="<?= $this->basePath('public/js/readr.js') ?>"></script>

</head>
<body>

	<?= $this->content ?>

</body>
</html>