<!DOCTYPE html>
<html>
<head>

	<meta charset="utf-8">
	<title><?= $this->title ?></title>

	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,400italic,600italic">
	<link rel="stylesheet" type="text/css" href="<?= $this->basePath('public/css/readr.css') ?>">

	<script type="text/javascript" src="<?= $this->basePath('public/js/jquery.min.js') ?>"></script>
	<script type="text/javascript" src="<?= $this->basePath('public/js/underscore-min.js') ?>"></script>
	<script type="text/javascript" src="<?= $this->basePath('public/js/underscore.string.min.js') ?>"></script>
	<script type="text/javascript" src="<?= $this->basePath('public/js/moment.min.js') ?>"></script>
	<script type="text/javascript" src="<?= $this->basePath('public/js/backbone-min.js') ?>"></script>
	<script type="text/javascript" src="<?= $this->basePath('public/js/readr.js') ?>"></script>

</head>
<body>

	<?= $this->content ?>

</body>
</html>