<div class="app">

	<header class="app-header app-navbar">

		<h1>
			<a href="<?= $this->basePath() ?>">Readr</a>
		</h1>

		<ul class="nav">
			<li><a href="<?= $this->basePath() ?>">Back</a></li>
			<?php if($this->username): ?>
			<li><a href="<?= $this->basePath('login/signout') ?>">Signout</a></li>
			<?php endif; ?>
		</ul>

	</header>

	<div class="app-body">

		<div class="settings">

			<h1>Authentication</h1>

			<form action="<?= $this->basePath('settings') ?>" method="post">

				<?php if (count($this->errors)): ?>
				<p class="error alert-block">
					<?= implode('<br/>', $this->errors) ?>
				</p>
				<?php endif; ?>

				<div class="form-item">
					<label class="form-label">Username</label>
					<div class="controls">
						 <input type="text" name="username" value="<?= $this->escape($this->username) ?>"/>
						 <span class="help-block">Leave blank to disable authentication</span>
					</div>
				</div>

				<div class="form-item">
					<label class="form-label">Password</label>
					<div class="controls">
						 <input type="password" name="password"/>
					</div>
				</div>

				<div class="form-item">
					<label class="form-label">Confirm</label>
					<div class="controls">
						 <input type="password" name="password_confirm"/>
					</div>
				</div>

				<div class="form-item">
					<div class="controls">
						 <div class="error error-block"></div>
						 <button type="submit" class="btn btn-primary">Save</button>
					</div>
				</div>

			</form>

		</div>

		<div class="settings">

			<h1>Import/Export OPML File</h1>

			<form action="<?= $this->basePath('settings/import') ?>" method="post" enctype="multipart/form-data">

				 <div class="form-item">
					 <label class="form-label">File</label>
					 <div class="controls input">
						 <input type="file" name="file"/>
					 </div>
				 </div>

				 <div class="form-item">
					 <div class="controls">
		 				<button type="submit" class="btn btn-primary">Import</button>
					 </div>
				</div>

			 </form>

		</div>

		<div class="settings">

			<h1>Version</h1>

			<ul>
				<li>
					Current version:
					<?= $this->release ?>
					(<?= $this->version ?>)
				</li>
			</ul>

		</div>

	</div>

</div>