<div class="app" id="readrApp">

	<header class="app-header app-navbar">
	
		<div class="group">
			<button class="item menu" data-toggle="mode" value="feeds">
				<i class="icon-menu"></i>
			</button>
			<h1 class="item">
				<a href="<?= $this->basePath() ?>">Readr</a>
			</h1>
			<h2 class="item">
				<button class="feed-title" data-toggle="mode" value="entries">All items</button>
			</h2>
		</div>
		
		<div class="group pull-right">
			
			<button type="button" class="item menu-collapse" data-toggle="collapse" data-target="#options">
				<i class="icon-settings"></i>
			</button>
			
			<div class="item item-collapse" id="options">
	
				<ul class="group nav">
					<li><button type="button" name="read" value="all" data-toggle="filter-status" class="active">All</button></li>
					<li><button type="button" name="read" value="0" data-toggle="filter-status">Unread</button></li>
					<li><button type="button" name="favorite" value="1" data-toggle="filter-status">Favorites</button></li>
					<li><button type="button" data-toggle="mark-read">Mark as read</button></li>
				</ul>
		
				<ul class="group nav">
					<li><button type="button" data-toggle="add-feed">Add subscription…</button></li>
				</ul>
				
				<ul class="group nav">
					<li><a href="<?= $this->basePath('settings') ?>">Settings</a></li>
					<?php if($this->username): ?>
					<li><a href="<?= $this->basePath('login/signout') ?>">Sign out</a></li>
					<?php endif; ?>
				</ul>
			
			</div>
		
		</div>

	</header>

	<div class="app-body">

		<aside class="col feeds">
			<ul>
				<li class="item">
					<button type="button" name="feed_id" value="all" data-toggle="filter-source">
						<span class="title">
							<i class="icon-home"></i>
							All items
						</span>
					</button>
				</li>
			</ul>
			<ul class="feeds-list"></ul>
		</aside>

		<aside class="col entries">
			<div class="search">
				<input type="search" name="q"/>
			</div>
			<ul class="entries-list"></ul>
			<div class="loading">
				<img src="<?= $this->basePath('public/img/loading.png') ?>" alt="" class="spin"/>
			</div>
		</aside>

		<article class="col entry"></article>

	</div>

</div>

<div class="modal" id="feedModal"></div>

<div class="modal" id="tagModal"></div>

<div class="modal" id="addModal">
	<form action="<?= $this->basePath('api/feeds') ?>" method="post" class="modal-content">
		<div class="modal-header">
			<h1>Add subscription</h1>
		</div>
		<div class="modal-body">
			<div class="form-item">
				<label class="form-label">Url</label>
				<div class="controls">
					<input type="url" name="url"/>
				</div>
			</div>
			<div class="form-item">
				<label class="form-label">Tags</label>
				<div class="controls">
					<input type="text" name="tags"/>
				</div>
			</div>
			<div class="error alert-block"></div>
		</div>
		<div class="modal-footer">
			<button type="button" data-toggle="close" class="btn">Cancel</button>
			<button type="submit" class="btn btn-primary">Add</button>
		</div>
	</form>
</div>

<script type="text/template" id="tagItem">
	<button type="button" data-toggle="subnav">
		<i class="icon-arrow"></i>
	</button>
	<button type="button" data-toggle="filter-source" name="tag" value="<%= name %>">
		<span class="title">
			<%- name %>
			<span class="count"></span>
		</span>
	</button>
	<div class="actions">
		<button type="button" data-toggle="edit" title="Edit…">
			<i class="icon-edit"></i>
		</button>
	</div>
</script>

<script type="text/template" id="feedItem">
	<button type="button" data-toggle="filter-source" name="feed_id" value="<%= id %>">
		<img src="<?= $this->basePath() ?>api/favicon/<%= id %>" class="icon-favicon" alt=""/>
		<span class="title">
			<%- title %>
			<span class="count"></span>
		</span>
	</button>
	<div class="actions">
		<button type="button" data-toggle="edit" title="Edit…">
			<i class="icon-edit"></i>
		</button>
	</div>
</script>

<script type="text/template" id="feedForm">
	<form class="modal-content">
		<div class="modal-header">
			<%= title %>
		</div>
		<div class="modal-body">
			<div class="form-item">
				<label class="form-label">Title</label>
				<div class="controls">
					<input type="text" name="title" value="<%- title %>"/>
				</div>
			</div>
			<div class="form-item">
				<label class="form-label">Url</label>
				<div class="controls">
					<input type="url" name="url" value="<%- url %>"/>
				</div>
			</div>
			<div class="form-item">
				<label class="form-label">Tags</label>
				<div class="controls">
					<input type="text" name="tags" value="<%- tags %>"/>
				</div>
			</div>
			<% if(last_error){ %>
			<p class="error alert-block">
				<%= last_error %>
			</p>
			<% } %>
		</div>
		<div class="modal-footer">
			<div class="pull-left">
				<button type="button" data-toggle="delete" class="btn btn-danger">Unsubscribe</button>
			</div>
			<button type="button" data-toggle="close" class="btn">Cancel</button>
			<button type="submit" class="btn btn-primary">Save</button>
		</div>
	</form>
</script>

<script type="text/template" id="tagForm">
	<form class="modal-content" action="<?= $this->basePath('api/tags') ?>/<%= encodeURIComponent(name) %>" method="post">
		<div class="modal-header">
			<%= name %>
		</div>
		<div class="modal-body">
			<div class="form-item">
				<label class="form-label">Name</label>
				<div class="controls">
					<input type="text" name="name" value="<%- name %>"/>
				</div>
			</div>
		</div>
		<div class="modal-footer">
			<div class="pull-left">
				<button type="button" data-toggle="delete" class="btn btn-danger">Delete</button>
			</div>
			<button type="button" data-toggle="close" class="btn">Cancel</button>
			<button type="submit" class="btn btn-primary">Save</button>
		</div>
	</form>
</script>

<script type="text/template" id="entryItem">
	<div class="actions">
		<i class="<% print(favorite == 1 ? 'icon-star-on' : 'icon-star') %>" data-toggle="favorite" title="Toggle favorite"></i>
		<i class="<% print(read == 1 ? 'icon-read' : 'icon-unread') %>" data-toggle="read" title="Toggle read"></i>
	</div>
	<h2 class="title"><%= title %></h2>
	<h3 class="feed"><%= feed_title %></h3>
	<time class="date" datetime="<%= moment.unix(date).format('YYYY-MM-DD HH:mm:ss') %>" title="<%= moment.unix(date).format('YYYY-MM-DD HH:mm:ss') %>">
		<%= moment.unix(date).fromNow() %>
	</time>
</script>

<script type="text/template" id="entry">
	<div class="wrapper">
		<h1 class="title">
			<a href="<%= link %>"><%= title %></a>
		</h1>
		<p class="details">
			<% if(author){ %>
			<span class="author">
				<%- author %>
			</span>
			-
			<% } %>
			<button type="button" data-toggle="filter-source" name="feed_id" value="<%= feed_id %>">
				<%- feed_title %>
			</button>
			-
			<time datetime="<%= moment.unix(date).format('YYYY-MM-DD HH:mm:ss') %>" title="<%= moment.unix(date).format('YYYY-MM-DD HH:mm:ss') %>">
				<%= moment.unix(date).fromNow() %>
			</time>
		</p>
		<div class="content">
			<%= content %>
		</div>
	</div>
</script>

<script type="text/javascript">
	var app = new readr.ReadrApp({
		el: document.getElementById('readrApp'),
		feeds: <?= json_encode($this->feeds) ?>,
		apiUrl: '<?= $this->basePath('api') ?>',
		settingsUrl: '<?= $this->basePath('settings') ?>',
		emulateHTTP: <?= $this->emulateHTTP ? 'true' : 'false' ?>,
		collapsed: <?= $this->collapsed ?>
	});
</script>